### ISSUE TITLE
SSL cert expired

### ISSUE THREAD

**Issue by liamg** [paultag/go-ykpiv#17] opened 2019-05-23 14:16 UTC
It looks like the SSL certificate has expired for `https://pault.ag`.

This means a go get fails a la:
```
package pault.ag/go/ykpiv: unrecognized import path "pault.ag/go/ykpiv" (https fetch: Get https://pault.ag/go/ykpiv?go-get=1: x509: certificate has expired or is not yet valid)
```

**Comment by paultag** [comment] 2019-05-23 14:20
Should be fixed now - I need to move this to S3.

**Comment by liamg** [comment] 2019-05-23 14:23
@paultag Thanks for the very speedy resolution! 👍

**Comment by anurag-prakash-singh** [comment] 2019-07-22 20:30
The certificate seems to have expired again (expiration happened at `Monday, July 22, 2019 at 7:34:50 AM Pacific`). Do you think you could renew it?

**Comment by paultag** [comment] 2019-07-22 20:32
I restarted nginx -- the issue is it does restart, but it doesn't autorestart. I need to move the whole thing to S3. I can likely do this next week. Thanks, all.

**Comment by paultag** [comment] 2019-07-22 20:32
(Resolved again, thank you).

**Closed by paultag** 2019-07-22 20:32 UTC
